### PR TITLE
add app manager page and fix bugs

### LINKED ISSUE #106: add app manager page and fix bugs
add app manager page and fix bugs

### PR DESCRIPTION
**Pull request by satoi-fish**
add app manager page and fix bugs

image

image

image

Close #106

### CODE REVIEW

File: web/src/api/app-manager/index.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  })
+}
+
+export const ModifyApplication = async (data: IManagerAppData[]) => {
+  return await Post("/api/Wechat/work/corp/apps/update", {
+    updateWorkWeChatCorpApplications: data,
+  })
+}
+
+export const GetSecretData = async (data: ISecretRequset) => {
```
Comment (0824F) [inline web/src/api/app-manager/index.ts:35]: PostSecretData

File: web/src/pages/app-manager/component/corp-app-dialog/index.tsx [hunk 2]
```diff
@@ -0,0 +1,139 @@
+import { Button, FormControlLabel, Switch, TextField } from "@mui/material"
+import {
+  IManagerAppKeyData,
+  IManagerCorpKeyData,
+  AddOrModify,
+  RowDataType,
+} from "../../../../dtos/app-manager"
+import useAction from "./hook"
+import styles from "./index.module.scss"
+const Add = (props: {
```
Comment (0824F) [inline web/src/pages/app-manager/component/corp-app-dialog/index.tsx:10]: 空行

**Review by Tracy-Wei — APPROVED** [review]
LGTM
