### PR TITLE
Fix data lost problem of flatten list for send target selector

### LINKED ISSUE #152: Fix data lost problem of flatten list for send target selector
Fix data lost problem of flatten list for send target selector
修复搜索用的平铺数据丢失问题

### PR DESCRIPTION
**Pull request by satoi-fish**
Fix data lost problem of flatten list for send target selector
修复搜索用户框数据丢失问题

Close #152

### CODE REVIEW

File: web/src/pages/enterprise/components/select-content/hook.ts [hunk 1]
```diff
@@ -366,57 +366,61 @@ export const useAction = (props: SelectContentHookProps) => {
     AppId: string,
     department: IDepartmentData,
     users: IDepartmentUsersData[],
-    defaultChild: IDepartmentAndUserListValue
+    defaultChild: IDepartmentAndUserListValue,
+    type: "fold" | "flatten" | "all"
```
Comment (0824F) [inline web/src/pages/enterprise/components/select-content/hook.ts:370]: 如果这个是更枚举会更好
