### PR TITLE
Fix routing issues

### LINKED ISSUE #7: Fix naming issues and ui styles

### PR DESCRIPTION
**Pull request by htllog**
Repair the problem that the highlighting in the project is not displayed, and add ui to the interface

image

Close #7

### CODE REVIEW

File: web/src/pages/main/index.tsx [hunk 1]
```diff
@@ -1,15 +1,32 @@
...
 import { routerArray } from "../../router/elementRoute";
-import { RoutePrperty } from "../../dtos/routeType";
+import { RouteItem } from "../../dtos/routeType";
+import useMainAction from "./hook";
 
 const Main = () => {
-  const routerTabBar = (list: RoutePrperty[]) => {
+  const { clickIndex, setClickIndex, location } = useMainAction();
+
+  useEffect(() => {
```
Comment (0824F) [inline web/src/pages/main/index.tsx:11]: hook里面都有useEffect了 为什么要写多次

**Review by 0824F — APPROVED** [review]
LGTM
